config/routes.rb
Adtlist::Application.routes.draw do
  mount Adtadmin::Engine, :at => "adtadmin"
  mount Usermanage::Engine => "/usermanage"
  devise_for :users
  resources :news_lists
  match '/news'=> 'main#news'
  match '/news/:id'=> 'main#news_show', :id => :id
  
  get '/userapi/getactiverandom' => 'userapi#getactiverandom'
  match '/userapi/v1' => 'userapi#v1'
  match '/about'=> 'about#index'

  resources :reviews

  
   root :to => 'main#estate'
   get "main/index"
  match '/estate'=> 'main#estate' 
  match '/news'=> 'main#news'
  match '/news/:id'=> 'main#news_show', :id => :id
  match '/search'=> 'main#search'
  match '/search/:category/:region'=> 'main#search', :region => :region, :category=>:category
  match '/:region/:altname'=> 'main#show', :region => :region, :altname => :altname
end

app/models/news_list.rb
class NewsList < ActiveRecord::Base
  attr_accessible :img_url, :short_text, :text, :title, :user_id, :isdelete, :isactive

  def self.all_active()
		NewsList.where( :isactive=>1)
  end

  def self.latest_active()
  	NewsList.where( :isactive=>1).order("created_at DESC").limit(4)
  end
end

app/controllers/news_lists_controller.rb
class NewsListsController < ApplicationController
  # GET /news_lists
  # GET /news_lists.json
  load_and_authorize_resource
  #layout "admin"
  def index
    @news_lists = NewsList.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news_lists }
    end
  end

  # GET /news_lists/1
  # GET /news_lists/1.json
  def show
    @news_list = NewsList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news_list }
    end
  end

  # GET /news_lists/new
  # GET /news_lists/new.json
  def new
    @news_list = NewsList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news_list }
    end
  end

  # GET /news_lists/1/edit
  def edit
    @news_list = NewsList.find(params[:id])
  end

  # POST /news_lists
  # POST /news_lists.json
  def create
    @news_list = NewsList.new(params[:news_list])

    respond_to do |format|
      if @news_list.save
        format.html { redirect_to @news_list, notice: 'News list was successfully created.' }
        format.json { render json: @news_list, status: :created, location: @news_list }
      else
        format.html { render action: "new" }
        format.json { render json: @news_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news_lists/1
  # PUT /news_lists/1.json
  def update
    @news_list = NewsList.find(params[:id])

    respond_to do |format|
      if @news_list.update_attributes(params[:news_list])
        format.html { redirect_to @news_list, notice: 'News list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_lists/1
  # DELETE /news_lists/1.json
  def destroy
    @news_list = NewsList.find(params[:id])
    @news_list.destroy

    respond_to do |format|
      format.html { redirect_to news_lists_url }
      format.json { head :no_content }
    end
  end
end

app/views/news_lists/_form.html.erb
<%= form_for(@news_list) do |f| %>
  <% if @news_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_list.errors.count, "error") %> prohibited this news_list from being saved:</h2>

      <ul>
      <% @news_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <div class="row">
    <div class="span1"><%= f.label :user_id %></div>
    <div class="span3"><%= f.number_field :user_id, :disabled=>true  %></div>

    <div class="span1"><%= f.label :isactive %></div>
    <div class="span1"><%= f.check_box :isactive %></div>

    <div class="span1"><%= f.label :isdelete %></div>
    <div class="span1"><%= f.check_box :isdelete %></div>

    <div class="span1"><%= f.label :img_url %></div>
    <div class="span3"><%= f.text_field :img_url %></div>
</div>

 <div class="row">
    <div class="span1"><%= f.label :title %></div>
    <div class="span4"><%= f.text_field :title %></div>

    <div class="span1"><%= f.label :short_text %></div>
    <div class="span5"><%= f.text_field :short_text %></div>
</div>
 <div class="row">
    <div class="span12"><%= f.cktext_area :text, :width => 620, :height => 600 %></div>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_lists/edit.html.erb
<h1>Editing news_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_list %> |
<%= link_to 'Back', news_lists_path %>

app/views/news_lists/index.html.erb
<h1>Редактирование/добавление новостей</h1>
<%= link_to 'Добавить', new_news_list_path,  :class => "btn btn-success" %>
<table>
  <tr>
    <th>Опубликовано</th>
    <th>Заголовок</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news_lists.each do |news_list| %>
  <tr>
    <td><%= news_list.isactive %></td>
    <td><%= news_list.title %></td>
    
   
  
    <td><%= link_to 'Show', news_list %></td>
    <td><%= link_to 'Edit', edit_news_list_path(news_list) %></td>
    <td><%= link_to 'Destroy', news_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'Добавить', new_news_list_path,  :class => "btn btn-success" %>

app/views/news_lists/new.html.erb
<h1>New news_list</h1>

<%= render 'form' %>

<%= link_to 'Back', news_lists_path %>

app/views/news_lists/show.html.erb
<p id="notice"><%= notice %></p>


 <div class="row">
    <div class="span8">
      <h2><%= @news_list.title %></h2>
      <%= @news_list.short_text %>
    </div>
    <div class="span4">
      <img src="<%= @news_list.img_url %>" class="news_list_img"> 
    </div>
  </div>
<hr>
<h2><%= @news_list.title %></h2>
<img src="<%= @news_list.img_url %>" class="news_list_img" align="left" > <%=raw @news_list.text %>


<hr>
<%= link_to 'Edit', edit_news_list_path(@news_list) %> |
<%= link_to 'Back', news_lists_path %>