config/routes.rb
Adtlist::Application.routes.draw do
  mount Adtadmin::Engine, :at => "adtadmin"
  mount Usermanage::Engine => "/usermanage"
  devise_for :users
  resources :news_lists
  match '/news'=> 'main#news'
  match '/news/:id'=> 'main#news_show', :id => :id
  
  get '/userapi/getactiverandom' => 'userapi#getactiverandom'
  match '/userapi/v1' => 'userapi#v1'
  match '/about'=> 'about#index'

  resources :reviews

  
   root :to => 'main#estate'
   get "main/index"
  match '/estate'=> 'main#estate' 
  match '/news'=> 'main#news'
  match '/news/:id'=> 'main#news_show', :id => :id
  match '/search'=> 'main#search'
  match '/search/:category/:region'=> 'main#search', :region => :region, :category=>:category
  match '/:region/:altname'=> 'main#show', :region => :region, :altname => :altname
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource :except => [:create]
  # GET /reviews
  # GET /reviews.json
  layout "admin"
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
        ReviewMailer.welcome_email(@review.phone, @review.post_id, @review.created_at).deliver
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :typereview_id %><br />
    <%= f.number_field :typereview_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :adress %><br />
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Typereview</th>
    <th>Name</th>
    <th>Phone</th>
    <th>Adress</th>
    <th>Description</th>
    <th>Post</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.typereview_id %></td>
    <td><%= review.name %></td>
    <td><%= review.phone %></td>
    <td><%= review.adress %></td>
    <td><%= review.description %></td>
    <td><a href="/posts/<%#= review.post.try(:id) %>"><%#= review.post.try(:title) %></a></td>
    <td><%= review.created_at %></td>
    
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Typereview:</b>
  <%= @review.typereview_id %>
</p>

<p>
  <b>Name:</b>
  <%= @review.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @review.phone %>
</p>

<p>
  <b>Adress:</b>
  <%= @review.adress %>
</p>

<p>
  <b>Description:</b>
  <%= @review.description %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>